version = 0.1
[default.deploy.parameters]
stack_name = "save-to-pocket-frontend"
resolve_s3 = true
s3_prefix = "save-to-pocket-frontend"
region = "us-west-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
