version = 0.1

[default]
[default.global.parameters]
stack_name = "save-to-pocket-frontend"
s3_prefix = "save-to-pocket-frontend"
region = "us-west-1"
image_repositories = []

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true