AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: API layer for save-to-pocket application

Parameters:
  ConfigStackName:
    Description: The name of the cloudformation stack which exports config settings
    Type: String
    Default: save-to-pocket-config

Globals:
  Function:
    Runtime: nodejs20.x
    Handler: index.handler
    Architectures:
      - x86_64

Resources:
  SaveItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/save-items
      Description: Saves an item to Pocket using the Pocket API
      Environment:
        Variables:
          POCKET_ACCESS_TOKEN_PARAM_NAME:
            Fn::ImportValue: !Sub '${ConfigStackName}-AccessToken'
          POCKET_CONSUMER_KEY_PARAM_NAME:
            Fn::ImportValue: !Sub '${ConfigStackName}-ConsumerKey'
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Sub
              - 'arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:${ParamName}'
              - ParamName:
                  Fn::ImportValue: !Sub '${ConfigStackName}-AccessToken'
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Sub
              - 'arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:${ParamName}'
              - ParamName:
                  Fn::ImportValue: !Sub '${ConfigStackName}-ConsumerKey'

Outputs:
  SaveItemFunction:
    Description: Save Item to Pocket Lambda Function
    Value: !GetAtt SaveItemFunction.Arn
